---
- name: Install Docker-py
  pip:
    name: docker-py
    state: present

- include: clean-up.yml

- include: install.yml

- include: admin.yml
  when: admin_user and admin_password is defined

- name: Define Endpoints
  shell: |
    curl --silent --show-error -o /dev/null -w "%{http_code}" {{ portainer_endpoint }}/endpoints \
      -H "Authorization: Bearer {{ (auth_token.content|from_json).jwt }}" \
      -F "Name={{ item.name }}" \
      -F "URL={{ item.url }}" \
      -F "EndpointType=1"
  args:
    warn: False
  with_items:
    - "{{ endpoints | list }}"
  when: endpoints is defined
  register: response
  #failed_when: response.stdout.find("200") != -1

- name: "TESTING, TEST"
  debug: msg="{{ response }}"

- name: Configure Portainer settings
  uri:
    url: "{{ portainer_endpoint }}/settings"
    method: PUT
    return_content: yes
    headers:
      Authorization: "{{ (auth_token.content|from_json).jwt }}"
    body_format: json
    body: "{{ lookup('template','settings.json.j2') }}"
  when: configure_settings

- include: registry.yml
  when: configure_registry