---
- name: Install Docker-py
  pip:
    name: docker-py
    state: present

- include: clean-up.yml

- include: install.yml

- include: admin.yml
  when: admin_user and admin_password is defined

- include: endpoints.yml
  when: endpoints is defined

- name: Configure Portainer settings
  uri:
    url: "{{ portainer_endpoint }}/settings"
    method: PUT
    return_content: true
    headers:
      Authorization: "{{ (auth_token.content|from_json).jwt }}"
    body_format: json
    body: "{{ lookup('template','settings.json.j2') }}"
  when: configure_settings

- include: registry.yml
  when: configure_registry
