---
- name: Install pre-reqs
  hosts: all
  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.pip
    - role: geerlingguy.docker
  vars:
    pip_install_packages:
      - name: docker-py
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-portainer
  vars:
    persistent_data_path: /opt/portainer:/data
    company_logo_url: http://example.com/foo.png
    portainer_endpoint: "http://{{ inventory_hostname }}:{{ host_port }}/api"
    admin_user: admin
    admin_password: admin
    endpoints:
      - {name: local, url: ""}
